version: "3.2"

services:

  commune:
    network_mode: host
    # image: commune:latest
    container_name: commune
    build: ./
    shm_size: '100gb' # for the shared memory size

    # expose ports for the frontend

      
  
    volumes:

      # COMMUNE VOLUME MOUNTS
      - ./commune:/commune/commune
      - ./subspace/pallets:/commune/subspace/pallets
      - ./frontend:/commune/frontend


      # LOCAL COMMUNE MOUNTS AND FILES
      - ./Makefile:/commune/Makefile 
      - ./setup.py:/commune/setup.py
      - ./commune.sh:/commune/commune.sh
      - ./requirements.txt:/commune/requirements.txt
      - ./README.md:/commune/README.md
      - ./scripts:/commune/scripts
      - ./poetry.lock:/commune/poetry.lock
      - ./pyproject.toml:/commune/pyproject.toml

      # DOCKER MOUNTS TO CONTROL DOCKER FROM WITHIN THE CONTAINER
      - /var/run/docker.sock:/var/run/docker.sock # MOUNT THE DOCKER SOCKET
      - /usr/bin/docker:/usr/bin/docker # MOUNT THE DOCKER BINARY
      
      # FILE SYSTEM MOUNTS
      - /tmp:/tmp # MOUNT THE TEMPORARY FILE
      - ~/.commune:/root/.commune
      - ~/.bittensor:/root/.bittensor

    command: bash -c "cd /commune; chmod +x /commune/scripts/*;/commune/scripts/startup.sh;"

  
